services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    environment:
      QUORUM_FLASK_ENV: testing
      QUORUM_DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/quorum
      QUORUM_ADMIN_PASSWORD: testadminpwd
      QUORUM_FLASK_SECRET: my-test-flask-secret
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: quorum
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 10

  selenium:
    image: selenium/standalone-chrome:117.0
    ports:
      - "4444:4444"
    depends_on:
      - web
