FROM python:3.10-slim

WORKDIR /app

COPY requirements/base.txt ./requirements/base.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r ./requirements/base.txt && \
    pip install gunicorn gevent

COPY app/ ./app/
COPY migrations ./migrations
COPY config.py ./config.py
COPY gunicorn.conf.py ./gunicorn.conf.py
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENV QUORUM_FLASK_ENV=production
ENV GUNICORN_CMD_ARGS="--config gunicorn.conf.py"

CMD ["./entrypoint.sh"]