services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    environment:
      QUORUM_FLASK_ENV: testing
      QUORUM_DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/quorum
      QUORUM_ADMIN_PASSWORD: ${QUORUM_ADMIN_PASSWORD}
      QUORUM_FLASK_SECRET: ${QUORUM_FLASK_SECRET}
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: quorum
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    working_dir: /mnt/locust
    environment:
      LOCUST_LOCUSTFILE: /mnt/locust/locustfile.py
      LOCUST_HOST: http://web:5000
    depends_on:
      - web
    tty: true
