services:
  web:
    environment:
      FLASK_ENV: testing
      DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/quorum
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"

  db_test:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: quorum_test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  tox:
    build:
      context: .
      dockerfile: Dockerfile.tox
    environment:
      FLASK_ENV: testing
      DATABASE_URL: postgresql://postgres:postgrespwd@db_test:5432/quorum_test
      BASE_URL: http://web:5000
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
    command: [ "-c", "flask db upgrade && exec tail -f /dev/null" ]
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      db_test:
        condition: service_healthy
      selenium:
        condition: service_started

  selenium:
    image: selenium/standalone-chrome:117.0
    ports:
      - "4444:4444"

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    working_dir: /mnt/locust
    environment:
      LOCUST_LOCUSTFILE: /mnt/locust/locustfile.py
      LOCUST_HOST: http://web:5000
    depends_on:
      - web
    tty: true

volumes:
  pgdata_test:

