services:
  web:
    environment:
      FLASK_ENV: testing
      FLASK_APP: run.py
      DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/quorum_test
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: quorum_test

  tox:
    build:
      context: .
      dockerfile: Dockerfile.tox
    environment:
      FLASK_ENV: testing
      DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/quorum_test
      BASE_URL: http://web:5000
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      - db
      - web
      - selenium

  selenium:
    image: selenium/standalone-chrome:117.0
    ports:
      - "4444:4444"

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    working_dir: /mnt/locust
    environment:
      LOCUST_LOCUSTFILE: /mnt/locust/locustfile.py
      LOCUST_HOST: http://web:5000
    depends_on:
      - web
    tty: true



