services:
  web:
    environment:
      FLASK_APP: run.py
      FLASK_ENV: testing
      DATABASE_URL: postgresql://postgres:testpwd@db:5432/quorum_test

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: quorum_test
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome:117.0
    ports:
      - "4444:4444"

  tox:
    build: 
      context: .
      dockerfile: Dockerfile.tox
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      FLASK_ENV: testing
      BASE_URL: http://web:5000
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      DATABASE_URL: postgresql://postgres:testpwd@db:5432/quorum_test
    volumes:
      - .:/app
    depends_on:
      - web
      - selenium
      - db

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"  # exposes Locust web UI at http://localhost:8089
    volumes:
      - .:/mnt/locust
    working_dir: /mnt/locust
    environment:
      LOCUST_LOCUSTFILE: /mnt/locust/locustfile.py
      LOCUST_HOST: http://web:5000
    depends_on:
      - web
    tty: true

volumes:
  pgdata_test: