"""initial_schema

Revision ID: ba2444ddeb3e
Revises: 
Create Date: 2025-10-27 23:49:05.996071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2444ddeb3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_meeting_code'), 'meetings', ['meeting_code'], unique=True)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('token_lookup_key', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'token_lookup_key', name='uq_meeting_token')
    )
    op.create_index('idx_checkins_meeting', 'checkins', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_checkins_token_lookup_key'), 'checkins', ['token_lookup_key'], unique=False)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_polls_meeting', 'polls', ['meeting_id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=1), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'checkin_id', name='uq_poll_checkin')
    )
    op.create_index('idx_poll_votes_checkin', 'poll_votes', ['checkin_id'], unique=False)
    op.create_index('idx_poll_votes_poll', 'poll_votes', ['poll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_poll_votes_poll', table_name='poll_votes')
    op.drop_index('idx_poll_votes_checkin', table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index('idx_polls_meeting', table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_checkins_token_lookup_key'), table_name='checkins')
    op.drop_index('idx_checkins_meeting', table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_meetings_meeting_code'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###