"""Initial schema

Revision ID: 18ae90f06ad4
Revises: 
Create Date: 2025-06-07 17:11:31.854785

"""
from alembic import op
import sqlalchemy as sa

from app.models import TZDateTime

# revision identifiers, used by Alembic.
revision = '18ae90f06ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', TZDateTime(timezone=True), nullable=False),
    sa.Column('end_time', TZDateTime(timezone=True), nullable=False),
    sa.Column('meeting_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_code')
    )
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', TZDateTime(timezone=True), nullable=False),
    sa.Column('vote_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_token')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index('idx_checkins_meeting', ['meeting_id'], unique=False)

    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=1), nullable=False),
    sa.Column('vote_token', sa.String(), nullable=False),
    sa.Column('timestamp', TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.create_index('idx_poll_votes_poll', ['poll_id'], unique=False)
        batch_op.create_index('idx_poll_votes_token', ['vote_token'], unique=False)
        batch_op.create_index('ix_poll_votes_poll_id_vote_token', ['poll_id', 'vote_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index('ix_poll_votes_poll_id_vote_token')
        batch_op.drop_index('idx_poll_votes_token')
        batch_op.drop_index('idx_poll_votes_poll')

    op.drop_table('poll_votes')
    op.drop_table('polls')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index('idx_checkins_meeting')

    op.drop_table('checkins')
    op.drop_table('meetings')
    # ### end Alembic commands ###
